### ISSUE TITLE
Support all server and socket event

### ISSUE THREAD

**Issue by yboujraf** [svrooij/tcp-server#4]
Dear @svrooij 

It will be great if your library could support all the server and socket events and could manage dns too for dns.lookup.

Best regards,
Youssef

**Comment by svrooij** [comment]
Isn't dns managed by the system?

Can you be a bit more specific about "all events"?

At the moment this really small library serves all my needs, but I'm willing to except PR's with your suggested changes

**Comment by yboujraf** [comment]
Dear @svrooij 

this is the events

### Class: net.Server

Event: 'close'
Event: 'connection'
Event: 'error'
Event: 'listening'


### Class: net.Socket

new net.Socket([options])
Event: 'close'
Event: 'connect'
Event: 'data'
Event: 'drain'
Event: 'end'
Event: 'error'
Event: 'lookup'
Event: 'ready'
Event: 'timeout'

I 'd like to manage and trig an event each time I got one of the events and log it 

The deal is for server and client as well and options in json file

### Network Library needs to support

+ TCP/IP Client AND Server using the library https://nodejs.org/api/net.html
+ UDP/datagram Client AND Server using the library https://nodejs.org/api/dgram.html
+ DNS (https://nodejs.org/api/dns.html )
+ OS to support Windows 10+, Linux and MacOS

I hope it could help you

Best Regards,
Youssef

**Comment by svrooij** [comment]
This library is 112 lines of TypeScript at the moment. That makes this library really easy to use. It uses some of those events in the library to expose the needed functionality.

If you want to use all those events, it might be better to just use the knowlage of this library for your one project. Or create a fork an add all those events.
